// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4brDdK_zyhopxv4QaNghAgy1GMuvUX6A',
    appId: '1:142497052230:web:912769e832cfdd52137c47',
    messagingSenderId: '142497052230',
    projectId: 'fluttergastos-7b824',
    authDomain: 'fluttergastos-7b824.firebaseapp.com',
    storageBucket: 'fluttergastos-7b824.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApzFmmpB0J5VICCLXAxELv66EnXJCj1jA',
    appId: '1:142497052230:android:229d9433125938dd137c47',
    messagingSenderId: '142497052230',
    projectId: 'fluttergastos-7b824',
    storageBucket: 'fluttergastos-7b824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TU_IOS_API_KEY_AQUI', // ← Configurar después
    appId: 'TU_IOS_APP_ID_AQUI',   // ← Configurar después
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_PROJECT_ID_AQUI',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_MACOS_API_KEY_AQUI', // ← Configurar después
    appId: 'TU_MACOS_APP_ID_AQUI',   // ← Configurar después
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_PROJECT_ID_AQUI',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TU_WINDOWS_API_KEY_AQUI', // ← Configurar después
    appId: 'TU_WINDOWS_APP_ID_AQUI',   // ← Configurar después
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_PROJECT_ID_AQUI',
  );
}